### ISSUE TITLE
FMU compliing error (from expert meeting demo)

### ISSUE THREAD

**Issue by JamesCheng21** [ibpsa/project1-boptest#104] opened 2019-08-31 20:39 UTC
The parser seems not working properly when trying to compile a model without read/write blocks. Ran `$ make compile_testcase_model TESTCASE=testcase_bestest_air` and got 

> Traceback (most recent call last):
  File "compile_fmu.py", line 19, in <module>
    fmupath = compile_fmu()
  File "compile_fmu.py", line 14, in compile_fmu
    fmupath = parser.export_fmu(modelpath, [mopath])
  File "/usr/local/testing/parsing/parser.py", line 191, in export_fmu
    fmu_path, _ = write_wrapper(model_path, file_name, instances)
  File "/usr/local/testing/parsing/parser.py", line 164, in write_wrapper
    fmu_path = compile_fmu('wrapped', [wrapped_path]+file_name)
  File "/usr/local/JModelica/Python/pymodelica/compiler.py", line 146, in compile_fmu
    separate_process, jvm_args)       
  File "/usr/local/JModelica/Python/pymodelica/compiler.py", line 255, in _compile_unit
    compiler_options, compile_to, compiler_log_level, jvm_args)
  File "/usr/local/JModelica/Python/pymodelica/compiler.py", line 371, in compile_separate_process
    return log.end();
  File "/usr/local/JModelica/Python/pymodelica/compiler_logging.py", line 306, in end
    raise CompilerError(errors, warnings)
pymodelica.compiler_exceptions.CompilerError: 
1 error(s) and 0 warning(s) found:
Syntax error at line 6, column 1, in file 'wrapped.mo':
     Unexpected token: "end wrapped"

**Comment by SenHuang19** [comment] 2019-10-21 21:41
this is Duplicate of #115

**Closed by SenHuang19** 2019-10-21 21:41 UTC
