### ISSUE TITLE
Questions regarding weather forecast and pulling results

### ISSUE THREAD

**Issue by MaPaKo** [ibpsa/project1-boptest#439] opened 2022-06-17 12:50 UTC
1) Could you provide an example of how to access weather forecasts? I could not figure out how to do it. 

2) I noticed that _requests.put("{0}/results"...)_ returns results with a time step of 30 sec, independently of the chosen time step for the simulation. Is there a way to change this?

**Comment by JavierArroyoBastida** [comment] 2022-06-17 14:14
Hey @MaPaKo, please check out [this tutorial](https://github.com/ibpsa/project1-boptest/blob/master/docs/workshops/BS21Workshop_20210831/Introduction_to_the_BOPTEST_framework.ipynb). Part 4 shows an example of how to obtain forecast (titled with "Try using forecasts"). Note that the API in that tutorial slightly changes by adding the `testid` to all request calls because it is using the service version of BOPTEST. However, all the rest should work the same when using BOPTEST locally on your laptop. 
As for your other question, I'm afraid that the granularity of the results will always be 30 seconds unless you choose a step shorter than 30 seconds in which case you'll get the results at the time intervals used by integration when simulating. Can you confirm this @dhblum? If what you need is a longer step period you can always post-process the results.

**Comment by dhblum** [comment] 2022-06-17 19:01
@JavierArroyoBastida @MaPaKo Confirmed.

**Comment by JavierArroyoBastida** [comment] 2022-06-17 19:07
Thanks @dhblum!

**Comment by dhblum** [comment] 2022-08-01 01:57
Resolving since pointed to documentation, and can also look at new user guide [here](https://ibpsa.github.io/project1-boptest/docs-userguide/api.html#get-forecast).

**Closed by dhblum** 2022-08-01 01:57 UTC
