### ISSUE TITLE
TestCase: Bestest Hydronic pump control

### ISSUE THREAD

**Issue by haraldwalnum** [ibpsa/project1-boptest#274] opened 2021-01-21 06:40 UTC
@dhblum @JavierArroyoBastida . As discussed yesterday I had some issues in controlling the pump on/off in the besttest hydronic testcase. I have tried to reproduce the issue in a simple test setup. I run the emulator with 3600s control step, turning the pump on/off for each step. The results are show below. One can see that ovePump_u and reaPump_y follows the control signal, but reaPPum_y consumes power more "randomly". This is also reflected by the gas consumed by the heater (reaQHea_y). 

![pumpTest](https://user-images.githubusercontent.com/53710940/105298985-c3165f00-5bba-11eb-8283-5acf5bfe579b.png)

I have also attached the code I used to run the test.
[pumpTest.txt](https://github.com/ibpsa/project1-boptest/files/5847349/pumpTest.txt)

**Comment by JavierArroyoBastida** [comment] 2021-01-21 12:46
Thanks @haraldwalnum for sharing the issue and script, I could easily reproduce the problem. I've been doing some testing on this and it's indeed an awkward behavior. I'm afraid I've not been able to realize the source of the problem, but have two comments on this:
1. Not sure if we're checking out the right commit of IDEAS for this testcase: we're using now `a91fd24d97a9dff737501a94cb6387530d618f6c` but I couldn't find that commit in the IDEAS library... not sure where it's coming from, maybe it's just me but just couldn't find it. I think we should check out: `f90badebc912251714a4ca93c86739cca34ea044`. Still, nothing has changed when checking out the new commit. 
2. I have extended the model to have a "debug model" that reads more variables which might help us to figure out what's going on. Basically, I've added read blocks for the integer that sets the pump stage, the pressure difference in the pump and the normalized pump speed. This debug model looks as follows:

![image](https://user-images.githubusercontent.com/22677958/105339916-8314a380-5bdd-11eb-9bb0-f09aa6ce6634.png)

See results here (also with indoor temperature):

![image](https://user-images.githubusercontent.com/22677958/105340692-83616e80-5bde-11eb-8e6e-d260742d23d2.png)

What is interesting from here is that the integer variable that sets the pump stage is already corrupted, which indicates that the problem comes from the `realToInteger`. The doc of this model:

<img src="https://user-images.githubusercontent.com/22677958/105343463-f28c9200-5be1-11eb-9160-a924bc852f53.png" width="600">

Where you can see that there is not definition of the output value when `u=0`, which I thought could be the origin of the problem. I changed the model in this branch of ideas: https://github.com/open-ideas/IDEAS/tree/issue1191_boptestBestestControl, to use a boolean threshold instead. Looking like:
![image](https://user-images.githubusercontent.com/22677958/105351693-2f11bb00-5bed-11eb-8669-d43c50019861.png)

but not improving results:
![image](https://user-images.githubusercontent.com/22677958/105351742-42248b00-5bed-11eb-87ef-ed756fddb094.png)

I'll keep trying when time allows. 
I'm also adding @Mathadon in the loop since this relates to https://github.com/open-ideas/IDEAS/issues/1191.

**Comment by JavierArroyoBastida** [comment] 2021-01-21 14:57
I have increased the boolean threshold in `greThr` to be `0.1` instead of `0`, just in case the problem could come from any kind of computational noise. Still the exact same result.

**Comment by JavierArroyoBastida** [comment] 2021-01-21 15:41
Changing the pump input to be continuous instead of integer to select stage seems to solve the problem. See model:

![image](https://user-images.githubusercontent.com/22677958/105372735-34c7ca80-5c06-11eb-946f-10a38e6cf866.png)

and output from @haraldwalnum's script now:
![image](https://user-images.githubusercontent.com/22677958/105372957-6fc9fe00-5c06-11eb-956c-f5a0938729b2.png)

I see this as a fair solution, although there are some things to take into account:

1. User would be able to modulate the pump. Not sure whether that's an advantage or a disadvantage. It relates to our dilemma on what can be measured/controlled in the emulators. 
2. Other emulators should be revised like the `bestest_hydronic_heat_pump` which also uses integers to control pump stage. 
3. The most important one: it is annoying not to know what was causing the problem!

**Comment by dhblum** [comment] 2021-01-21 15:52
Thanks @haraldwalnum for reporting and @JavierArroyoBastida for looking into it.  Also, indeed putting a first order filter before the real-to-integer block helps too (see results below from Harald's script).  FYI Applying the filter after the real-to-integer block does not help, including using the filter within the pump itself.

<img width="445" alt="Screen Shot 2021-01-21 at 10 49 22 AM" src="https://user-images.githubusercontent.com/19480999/105375154-793b7200-5bd6-11eb-9e86-b2f4a10d99fc.png">

![pumpTest](https://user-images.githubusercontent.com/19480999/105375233-8b1d1500-5bd6-11eb-95bb-0e884ca4736a.png)

**Comment by dhblum** [comment] 2021-01-21 16:08
My feeling is that it has to do with event updates related to the real-to-integer block.  The filter forces a state event and using the continuous signal removes the real-to-integer block altogether.  See also https://github.com/ibpsa/project1-boptest/issues/213 for relation.

**Comment by JavierArroyoBastida** [comment] 2021-01-21 16:38
Thanks @dhblum, that helps me understand a bit better. 
Still, we need to make a decision on how to solve this. We can either use the filter or the continuous actions. Do you have any preference? or maybe another suggestion to try out?

**Comment by haraldwalnum** [comment] 2021-01-21 16:56
In my opinion, the filter solution is the best. It solves point 1 of Javier. However, point 2 is still valid an I guess it can occur in all emulators using real to integer blocks or hysteresis (which is common in controllers). Maybe also in other cases?

**Comment by SenHuang19** [comment] 2021-01-21 16:57
a step function is generally approximated as a ramping function in JModelica. So whether the event is triggered or not depends on how the step function is interpolated, which is associated with the simulation interval the solver selects. Adding a filter basically defines how the step function should be interpolated but my concern is that it may add artificial delays

**Comment by dhblum** [comment] 2021-01-21 19:07
I've been spending some time trying to get even further to the root of the issue.  Specifically, why potential events aren't checked for at the start of a simulation step, when that simulation step could have changed inputs from the last one?  So I've gone digging through the ``pyfmi`` code.

In BOPTEST's ``testcase.py``, simulation at each step occurs using the ``fmu.simulate()`` function, which is a high-level function that wraps a number of FMI functions together depending on whether the FMU is a ME or CS.  In our case, we have an ME.  So the ``fmu.simulate()`` function instantiates an instance of class ``AssimuloFMIAlg`` from ``fmi_algorithm_drivers.py``, uses it to prepare the model for a simulation step given inputs and options, and then takes the simulation step by using Assimulo's CVODE solver and associated interface in ``simulation/assimulo_interface.py``.  Anyway, in ``fmi_algorithm_drivers.py`` line ~338, there is the following code:

```
        #See if there is an time event at start time
        if isinstance(self.model, fmi.FMUModelME1):
            event_info = self.model.get_event_info()
            if event_info.upcomingTimeEvent and event_info.nextEventTime == model.time:
                self.model.event_update()
```
My inclination seems right, that in the preparation for the simulation step, there should be a check of an event at start time (which would occur if the input changed values from the last step).  But, notice that the ``if`` clause only does so for an ME1.  It skips this check altogether for ME2.  

So, I did a test where upon building the testcase docker image I add the following to ``fmi_algorithm_drivers.py`` after the above code, to basically do the same for ME 2:

```
        if isinstance(self.model, fmi.FMUModelME2):
            self.model.event_update()         
```

Then, I compiled the testcase (original, with the real-to-integrator block and without the filter), ran Harald's script, and BINGO:

![pumptTest2](https://user-images.githubusercontent.com/19480999/105399358-831e9e80-5bf1-11eb-9bf4-ed73d02b3a7e.png)

**Comment by JavierArroyoBastida** [comment] 2021-01-22 09:39
Wow @dhblum this is great, thanks for taking the time to figure it out.
Does this mean that we can just use the new Dockerfile with the pyfmi edit? 
It looks like a pyfmi bug to me. Do you Know by any chance what's the difference between FMU1 and FMU2? From the source-code definition I see:

FMUModelME1: An FMI Model loaded from a DLL. (see [here](https://github.com/modelon-community/PyFMI/blob/88657958d2742efcaba3852b9edfea89997baeb8/src/pyfmi/fmi.pyx#L3138))
FMUModelME2: Model-exchange model loaded from a dll. (see [here](https://github.com/modelon-community/PyFMI/blob/88657958d2742efcaba3852b9edfea89997baeb8/src/pyfmi/fmi.pyx#L7357))

But that doesn't say much to me.

**Comment by dhblum** [comment] 2021-01-22 14:17
@JavierArroyoBastida Yes, I think the new Dockerfile should be sufficient.  But I'd like to repeat the small test I did in #213 to double check on that case, and I think also report an issue with pyfmi development to see what they say.  And maybe @haraldwalnum wants to try his previous test case that ran into problems that prompted that issue.

The 1 and the 2 specify which version of the FMI standard is supported.

**Comment by dhblum** [comment] 2021-01-22 18:09
Another update.  Indeed based on a simpler tests the fix described above helps.  Consider the model:

<img width="842" alt="Screen Shot 2021-01-22 at 12 55 20 PM" src="https://user-images.githubusercontent.com/19480999/105526971-1b2f8d00-5cb1-11eb-9d34-f6e96d15b44e.png">


Compiling into an ME2 FMU and simulating in three steps of 100 each with changes in input values in each of u1,u2,u3 at the start of each step yields the following:

![eventTest](https://user-images.githubusercontent.com/19480999/105528371-ea505780-5cb2-11eb-976b-067586015d8a.png)

**Comment by haraldwalnum** [comment] 2021-01-25 11:41
Thanks again @dhblum . This fix works on my test case as well.

**Comment by dhblum** [comment] 2021-01-25 16:21
@haraldwalnum Great!  I've reported this issue to the pyfmi repo in https://github.com/modelon-community/PyFMI/issues/64.  

If a fix is indeed necessary, it will be made in a future version of pyfmi.  Currently, the BOPTEST Docker uses the last trunk of JModelica.org and the pyfmi version included therein.  There's already an incomplete issue https://github.com/ibpsa/project1-boptest/issues/146 to migrate this to a stand-alone pyfmi install, where we could then utilize any new version of pyfmi that would contain any fix.  But there were some challenges to migrating to a stand-alone pyfmi install that needed to be resolved.  I've actually made some good progress on this but haven't gotten a chance to formalize and report back to that issue.  Will aim to do so soon.  

In the meantime of hearing back from pyfmi developers and migrating the BOPTEST container to a stand-alone pyfmi install, I suggest using the patch I propose in the Dockerfile here https://github.com/ibpsa/project1-boptest/tree/issue274_hydronicPumpControl.  Any thoughts on this?

**Comment by dhblum** [comment] 2021-01-25 16:22
EDIT: I referenced the wrong pyfmi issue in the above comment.  It is actually: https://github.com/modelon-community/PyFMI/issues/72.

**Comment by haraldwalnum** [comment] 2021-01-25 18:22
Sounds good to me.

**Comment by dhblum** [comment] 2021-02-09 20:28
Closed by https://github.com/ibpsa/project1-boptest/pull/284.

**Closed** 2021-02-09 20:28 UTC
